baseURL: "http://machoo-l.github.io"
languageCode: 'en-us'
title: Matthew Blog
theme: PaperMod
author: Matthew Le
Paginate: 100
# Automatically add content sections to main menu
SectionPagesMenu: main